# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='documents/%Y%m%d/')),
                ('uploaded_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('PAP', 'Pending Approval'), ('PAC', 'Pending Acceptance'), ('active', 'Active'), ('closed', 'Closed')], max_length=255)),
            ],
        ),
    ]
