# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app_v2', '0003_auto_20171126_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
